# Use the official MySQL image as the base image
FROM mysql:8.0

# Set environment variables
# MYSQL_ROOT_PASSWORD: The password for the root user
ENV MYSQL_ROOT_PASSWORD=my-stoic-world-123

# Expose port 3306 to allow communication to/from the server
EXPOSE 3306
